apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: springapp-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: springapp
    spec:
      containers:
      - name: springapp-container1
        image: 4482/springapp:{{ .Values.imVersion }}
        ports:
        - containerPort: 8181

